---
title: "Vetenskaplig världsbild"
author: "eriknilsson"
date: 2018-02-17
categories: ["Astronomi", "Biologi", "Geologi", "Vetenskapsteori"]
tags: ["Ontologi", "Vetenskap", "Podcast", "Media"]
---

# Skala

### En film om skala och tiopotenser

<iframe width="694" height="520" src="https://www.youtube.com/embed/0fKBhvDjuy0" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>

POWERS OF TEN © 1977 EAMES OFFICE LLC (Available at www.eamesoffice.com)

### Interaktiv animation om skala

[Länk till en interaktiv animation av universums skala av Cary Huang](http://htwins.net/scale2/)

### Jämförelse av planeters och stjärnors storlekar

En till film om storlek: <iframe width="694" height="555" src="https://www.youtube.com/embed/HEheh1BH34Q" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>

# Statististisk termodynamik

Scrödinger.

# Paradigm och falsifiering

Kuhn och Popper.

# Universum och astrobiologi

"Astronomy 141" är bra grunläggande föreläsningar. "The topics covered in this course lie at the interfaces between astronomy, chemistry, biology, geology, and the earth and planetary sciences."

Länk: <http://www.astronomy.ohio-state.edu/~pogge/Ast141/>

## Exoplaneter

Nedan är en animering som visar exoplaneter sedda med Keplerteleskopet. Vårt eget solsystem ses till höger i bilden. Avstånden är inte skalenliga men planeternas relativa storlek visas, liksom deras temperaturer.

<iframe width="655" height="368" src="https://www.youtube.com/embed/_DnDeBa0KFc" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>

</br>

[Länk: NASA om exoplaneter](https://exoplanets.nasa.gov/)
